spring:
    application:
        name: GestorDocumentalBackEnd
    datasource:
        url: jdbc:mysql://localhost:3306/gestor_documental?CreateDatabaseIfNotExist=true&serverTimezone=UTC
        username: root
        password: infinity
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        show-sql: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        open-in-view: true
security:
    jwt:
        expiration-in-minutes: 380
        secret: TeTocasPorLasNochesComoUnPutoMacacoCabronTeTocasPorLasNochesComoUnPutoMacacoCabron
logging:
    level:
      org.springframework.integration: DEBUG